### ISSUE TITLE
GWT Compiler Exception for Vaadin 8.3.x

### ISSUE THREAD

**Issue by dangerground** [TatuLund/GridFastNavigation#46]
Using Vaadin 8.3.x the gwt-compiler (2.8.2) seems to dislike the native Java-code in GridViolators. 

```
Caused by: java.lang.ClassCastException: com.google.gwt.dev.jjs.ast.JClassType cannot be cast to com.google.gwt.dev.jjs.ast.JInterfaceType
        at com.google.gwt.dev.jjs.impl.ReferenceMapper.get(ReferenceMapper.java:160)
        at com.google.gwt.dev.jjs.impl.ReferenceMapper.createMethod(ReferenceMapper.java:246)
        at com.google.gwt.dev.jjs.impl.ReferenceMapper.get(ReferenceMapper.java:110)
        at com.google.gwt.dev.jjs.impl.GwtAstBuilder$AstVisitor$JsniReferenceCollector.endVisit(GwtAstBuilder.java:315)
        at com.google.gwt.dev.js.ast.JsNameRef.traverse(JsNameRef.java:113)
        at com.google.gwt.dev.js.ast.JsVisitor.doTraverse(JsVisitor.java:467)
        ... 54 more
   [ERROR] at GridViolators.java(38): escallator.@com.vaadin.client.widgets.Escalator::getBody()
      com.google.gwt.dev.js.ast.JsNameRef
   [ERROR] at GridViolators.java(38): escallator.@com.vaadin.client.widgets.Escalator::getBody()()
      com.google.gwt.dev.js.ast.JsInvocation
   [ERROR] at GridViolators.java(38): conBody = escallator.@com.vaadin.client.widgets.Escalator::getBody()()
      com.google.gwt.dev.js.ast.JsVars$JsVar
   [ERROR] at GridViolators.java(38): var conBody = escallator.@com.vaadin.client.widgets.Escalator::getBody()()
      com.google.gwt.dev.js.ast.JsVars
   [ERROR] at GridViolators.java(33): {
  var cfh = grid.@com.vaadin.client.widgets.Grid::cellFocusHandler;
  var row = cfh.@com.vaadin.client.widgets.Grid.CellFocusHandler::rowWithFocus;
  var contWithFocus = cfh.@com.vaadin.client.widgets.Grid.CellFocusHandler::containerWithFocus;
  var escallator = grid.@com.vaadin.client.widgets.Grid::getEscalator()();
  [...]
}

      com.google.gwt.dev.js.ast.JsBlock
   [ERROR] at GridViolators.java(33): function(grid){
  var cfh = grid.@com.vaadin.client.widgets.Grid::cellFocusHandler;
  var row = cfh.@com.vaadin.client.widgets.Grid.CellFocusHandler::rowWithFocus;
  var contWithFocus = cfh.@com.vaadin.client.widgets.Grid.CellFocusHandler::containerWithFocus;
  var escallator = grid.@com.vaadin.client.widgets.Grid::getEscalator()();
  [...]
}

      com.google.gwt.dev.js.ast.JsFunction
   [ERROR] at GridViolators.java(33): public static final native int getFocusedRow(Grid<?> grid);
      org.eclipse.jdt.internal.compiler.ast.MethodDeclaration

```

**Comment by TatuLund** [comment]
Thanks for reporting. I just re-compiled the latest version of the add-on with Vaadin 8.3.1 and I did not have any problems.

**Comment by dangerground** [comment]
I'll try to provide more information. I'm using gradle 4.5 using a custom task to invoke the gwt compiler

```
def targetDir = new File("$buildDir/vaadin/widgetsets/")
task widgetset(type: JavaExec) {
    def widgetsetClass = 'example.webapp.vaadin.widgetset.widgetset'

    classpath = sourceSets.main.runtimeClasspath
    classpath += files("src/main/java")
    classpath += sourceSets.main.compileClasspath
    classpath += configurations.widgetset

    jvmArgs = ['-Xmx1024M', '-Xss1024k'/*, '-Dgwt.persistentunitcache=false'*/]

    main = 'com.google.gwt.dev.Compiler'

    args += [
            '-logLevel', 'INFO',
            '-workDir', "$buildDir/tmp/widgetset",
            '-gen', "$buildDir/generated/java",
            '-war', targetDir.absolutePath,
            widgetsetClass
    ]
}
```

and my widgetset simplified looks like this at the moment

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module PUBLIC "-//Google Inc.//DTD Google Web Toolkit 2.5.1//EN"
        "http://google-web-toolkit.googlecode.com/svn/tags/2.5.1/distro-source/core/src/gwt-module.dtd">
<module>

    <!-- Inherit DefaultWidgetSet -->
    <inherits name="com.vaadin.DefaultWidgetSet" />
    <inherits name="com.vaadin.v7.Vaadin7WidgetSet"/>

    <inherits name="org.vaadin.hene.popupbutton.widgetset.PopupbuttonWidgetset"/>

    <inherits name="fi.jasoft.dragdroplayouts.DragDropLayoutsWidgetSet"/>

    <inherits name="org.vectomatic.libgwtsvg"/>

    <inherits name="org.vaadin.patrik.GridFastNavigationWidgetSet" />

    <inherits name="org.vaadin.cropper.WidgetSet" />

    <inherits name="elemental.Elemental"/>
</module>
```

anything else I can provide or test to pinpoint the problem?

**Comment by TatuLund** [comment]
Oh my, I am not familiar with Gradle, but with some Googling I saw this, someone getting similar error in Gradle setup with JSNI. So yes, there must be some sort of config issue, but I really can't say more about details.

https://github.com/Putnami/putnami-gradle-plugin/issues/35

**Comment by dangerground** [comment]
Today I was able to create a minimal example to reproduce the issue outside of my project. The problem I could pinpoint is the "-war" argument. I can work around this issue, but I'd like to keep the generated files in the build folder instead of beside the sourcecode. Do you have some constraints regarding the deployment path? If you don't I'll probably have to file a bug in gwt itself.

Minimal example:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module PUBLIC "-//Google Inc.//DTD Google Web Toolkit 2.5.1//EN"
        "http://google-web-toolkit.googlecode.com/svn/tags/2.5.1/distro-source/core/src/gwt-module.dtd">
<module>
    <inherits name="com.vaadin.DefaultWidgetSet" />
    <inherits name="org.vaadin.patrik.GridFastNavigationWidgetSet" />
</module>
```

```
plugins {
    id "java-library"
}

dependencies {
        compileOnly "com.vaadin:vaadin-client:8.3.1"
        compileOnly "com.vaadin:vaadin-client-compiler:8.3.1"
        compileOnly "org.vaadin.patrik:GridFastNavigation:2.1.10"
}

repositories {
        jcenter()
        maven {
                url "http://maven.vaadin.com/vaadin-addons"
        }
}

task widgetset(type: JavaExec) {
    classpath = sourceSets.main.compileClasspath
    classpath += files("src/main/resources")

    def targetDir = new File("$buildDir/vaadin/widgetsets/")

    main = 'com.google.gwt.dev.Compiler'
    args = [
            '-logLevel', 'INFO',
            '-deploy', targetDir.absolutePath,
            '-extra', targetDir.absolutePath,
            'example.webapp.vaadin.widgetset.widgetset'
    ]
}

```
